### PR TITLE
Fix memory leak in readInBackgroundAndNotify method

### LINKED ISSUE #65: Memory leaks in DiagnosticsLogger.handlePipeNotification
I'm getting memory leaks DiagnosticsLogger.handlePipeNotification. I'm not sure if this is an actual leak or the NSData object being created is being added to an autorelease pool. Does anyone else experience this?

Screenshot 2020-04-25 at 11 15 09

### PR DESCRIPTION
**Pull request by AvdLee**
In the process of fixing #65 I've been optimizing our code a bit.

- [x] The queue is now using an autoreleasepool to make sure we release all memory correctly
- [x] Although used as a singleton we were retaining `self` quite a bit. Fixed this
- [x] We're no longer using the [readInBackgroundAndNotify](https://developer.apple.com/documentation/foundation/filehandle/1417635-readinbackgroundandnotify) method that was causing a memory leak. Instead, the `readabilityHandler` allows us to read new log values.

| Before | After |
| --- | --- |
| Screenshot 2020-05-25 at 16 02 25 | Screenshot 2020-05-25 at 16 02 09 |

Fixes #65

### CODE REVIEW

File: Sources/DiagnosticsLogger.swift [hunk 1]
```diff
@@ -134,7 +137,7 @@ extension DiagnosticsLogger {
     private func log(message: String, file: String = #file, function: String = #function, line: UInt = #line) {
         guard isSetup else { return assertionFailure() }
 
-        queue.async {
+        self.queue.async { [unowned self] in
```
Comment (WeTransferBot) [inline Sources/DiagnosticsLogger.swift:140]: - :warning: It is safer to use weak instead of unowned

File: Sources/DiagnosticsLogger.swift [hunk 2]
```diff
@@ -15,10 +15,13 @@ public final class DiagnosticsLogger {
...
 
-    private lazy var location: URL = FileManager.default.documentsDirectory.appendingPathComponent("diagnostics_log.txt")
+    private lazy var logFileLocation: URL = FileManager.default.documentsDirectory.appendingPathComponent("diagnostics_log.txt")
+    private var logFileHandle: FileHandle?
+
     private let inputPipe: Pipe = Pipe()
     private let outputPipe: Pipe = Pipe()
-    private let queue: DispatchQueue = DispatchQueue(label: "com.wetransfer.diagnostics.logger", qos: .utility, target: .global(qos: .utility))
+
+    private let queue: DispatchQueue = DispatchQueue(label: "com.wetransfer.diagnostics.logger", qos: .utility, autoreleaseFrequency: .workItem, target: .global(qos: .utility))
```
Comment (kairadiagne) [inline Sources/DiagnosticsLogger.swift:24]: Great, I did not know about `autoreleaseFrequency` so I learned something new! Just out of curiosity, do you know the difference between `qos` and `targetQueue` parameter?

Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift:24]: By using `targetQueue` you basically reuse and existing available queue with the same quality of service and dispatch to that linked thread. Otherwise, a new queue is generated with its own Thread. You can use this to minimize the total number of threads while still preserving the required execution semantics.

Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift:24]: We should, btw, do this way more often in our app! I'll see if I can do that as it's not that hard

File: Sources/DiagnosticsLogger.swift [hunk 3]
```diff
@@ -88,34 +91,34 @@ extension DiagnosticsLogger {
...
+        logFileHandle!.seekToEndOfFile()
+        logSize = Int64(logFileHandle!.offsetInFile)
         setupPipe()
         isSetup = true
         startNewSession()
     }
 
     internal func startNewSession() {
-        queue.async {
+        queue.async { [unowned self] in
```
Comment (kairadiagne) [inline Sources/DiagnosticsLogger.swift:121]: I really like were using `[unowned self]` when possible! Just to double-check: Here we use `[unowned self]` instead of `[weak self]`, because this is a singleton object, so we don't risk blocks being executed while the diagnostic logger object is already deallocated.

File: Sources/DiagnosticsLogger.swift [hunk 4]
```diff
@@ -189,7 +192,12 @@ private extension DiagnosticsLogger {
     func setupPipe() {
         guard !isRunningTests else { return }
 
-        let pipeReadHandle = inputPipe.fileHandleForReading
+        inputPipe.fileHandleForReading.readabilityHandler = { [weak self] handle in
```
Comment (kairadiagne) [inline Sources/DiagnosticsLogger.swift:195]: Nice!

File: Sources/DiagnosticsLogger.swift [hunk 5]
```diff
@@ -198,39 +206,18 @@ private extension DiagnosticsLogger {
...
-
+    private func handleLoggedData(_ data: Data) {
         outputPipe.fileHandleForWriting.write(data)
 
-        queue.async {
-            string.enumerateLines(invoking: { (line, _) in
-                self.log("SYSTEM: \(line)\n")
-            })
+        guard let string = String(data: data, encoding: .utf8) else {
+            return assertionFailure()
```
Comment (kairadiagne) [inline Sources/DiagnosticsLogger.swift:215]: Could we put a message here that describes what is the cause of the failure?

File: Sources/DiagnosticsLogger.swift (hunk 3 above)
Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift:121]: Exactly! The logger is always available in the same lifetime as the queue 🙂

File: Sources/DiagnosticsLogger.swift (hunk 5 above)
Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift:215]: Yes, definitely!

File: Sources/DiagnosticsLogger.swift [hunk 6]
```diff
@@ -84,38 +87,38 @@ extension DiagnosticsLogger {
...
+        logFileHandle!.seekToEndOfFile()
+        logSize = Int64(logFileHandle!.offsetInFile)
         setupPipe()
         isSetup = true
         startNewSession()
     }
 
     internal func startNewSession() {
-        queue.async {
+        queue.async { [unowned self] in
```
Comment (WeTransferBot) [inline Sources/DiagnosticsLogger.swift:121]: - :warning: It is safer to use weak instead of unowned

File: Sources/DiagnosticsLogger.swift (hunk 2 above)
Comment (kairadiagne) [reply Sources/DiagnosticsLogger.swift:24]: Thanks for explaining, that makes sense. Although I think it really depends on the context in which the dispatch queue is used. I need to refresh my knowledge on this but I remember from this [WWDC talk on GCD](https://developer.apple.com/videos/play/wwdc2017/706/)  that dispatching a lot of different task in your app to the same global queue can lead to similar issues with having too many threads as you can run into when you create many custom queues in your app.

Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift:24]: Yeah, it's worth spending some time on those talks for sure!
