### PR TITLE
Check available disk space before writing to the log

### LINKED ISSUE #37: Crash happening when there is no space left on the device
> *** -[NSConcreteFileHandle writeData:]: No space left on device

This is happening inside the `DiagnosticsLogger` on line 146, inside the log method. This method can be called from many places.

We basically need to check whether there's enough space left to write the logs.

### PR DESCRIPTION
**Pull request by AvdLee**
This fixes crashes happening for users that don't have enough space left on their device.

Fixes #37

### CODE REVIEW

File: Sources/DiagnosticsLogger.swift [hunk 1]
```diff
@@ -143,6 +143,9 @@ extension DiagnosticsLogger {
                 return assertionFailure()
         }
 
+        // Make sure we have more then 500MB space left
```
Comment (Boris-Em) [inline Sources/DiagnosticsLogger.swift]:
```suggestion
        // Make sure we have more than 500MB space left
```

File: Sources/DiagnosticsLogger.swift [hunk 2]
```diff
@@ -143,6 +143,9 @@ extension DiagnosticsLogger {
...
+        guard UIDevice.current.freeDiskSpaceInBytes > (500 * 1024) else { return }
```
Comment (kairadiagne) [inline Sources/DiagnosticsLogger.swift]: Just to make sure I understand it correctly. We check for the device disk space, because we can't catch the out of disk space exception in Swift? Also, I might be wrong, but don't we check here if there is more than 500kb space left instead of 500 MB?

Comment (Boris-Em) [inline Sources/DiagnosticsLogger.swift]: Isn't this .5MB?

Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift]: Yes, I'll update that!

Comment (AvdLee) [reply Sources/DiagnosticsLogger.swift]: Yes, I'll update that!

File: Sources/DiagnosticsLogger.swift [hunk 3]
```diff
@@ -143,6 +144,9 @@ extension DiagnosticsLogger {
                 return assertionFailure()
         }
 
+        // Make sure we enough disk space left. This prevents a crash due to a lack of space.
```
Comment (Boris-Em) [inline Sources/DiagnosticsLogger.swift]:
```suggestion
        // Make sure we have enough disk space left. This prevents a crash due to a lack of space.
```
