### PR TITLE
Include exceptions in the logs

### LINKED ISSUE #63: Add crashes to our logs
It would be great to include stacktraces of a crash in our Diagnostics report

https://stackoverflow.com/a/43202362/1485701

### PR DESCRIPTION
**Pull request by AvdLee**
This PR makes it possible to find back exceptions in the logs. It's not possible to log Swift errors but Objective-C exceptions will bring us a lot as well!

- [x] Include exceptions in log
- [x] Make use of the full page width for better viewing experience

image

Fixes #63

### CODE REVIEW

File: Sources/DiagnosticsLogger.swift [hunk 1]
```diff
@@ -113,11 +97,42 @@ extension DiagnosticsLogger {
...
+        standard.log(message)
+    }
+}
+
+// MARK: - Setup & Logging
+extension DiagnosticsLogger {
+
+    /// Creates a new section in the overall logs with data about the session start and system information.
+    func startNewSession() {
         queue.async { [unowned self] in
```
Comment (WeTransferBot) [inline Sources/DiagnosticsLogger.swift:136]: - :warning: It is safer to use weak instead of unowned

File: Example/Diagnostics-Example/ViewController.swift [hunk 2]
```diff
@@ -37,6 +37,11 @@ class ViewController: UIViewController {
         present(mail, animated: true)
     }
 
+    @IBAction private func crashTriggerButtonTapped(_ sender: Any) {
+        /// Swift exceptions can't be catched yet, unfortunately.
+        let array = NSArray(array: ["Antoine", "Boris", "Kaira"])
+        print(array.object(at: 4)) // Classic index out of bounds crash
```
Comment (Boris-Em) [inline Example/Diagnostics-Example/ViewController.swift:43]: Classic

File: Sources/DiagnosticsLogger.swift [hunk 3]
```diff
@@ -113,11 +98,42 @@ extension DiagnosticsLogger {
...
```
Comment (WeTransferBot) [inline Sources/DiagnosticsLogger.swift:137]: - :warning: It is safer to use weak instead of unowned
