### PR TITLE
Fix tests and test CI

### LINKED ISSUE #7: Add support for CocoaPods
Add support for CocoaPods

### LINKED ISSUE #8: Add support for Carthage
Add support for Carthage

### LINKED ISSUE #9: Add support for SPM
Add support for SPM

### LINKED ISSUE #10: Add CI
CI to run for PRs

### PR DESCRIPTION
**Pull request by AvdLee**
Let's see if CI succeeds

Fixes #10
Fixes #8 
Fixes #7 
Fixes #9

### CODE REVIEW

File: Example/Diagnostics-Example/AppDelegate.swift [hunk 1]
```diff
@@ -28,6 +28,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
         do {
             try DiagnosticsLogger.setup()
         } catch {
+            // swiftlint:disable nslog_prohibited
```
Comment (WeTransferBot) [inline Example/Diagnostics-Example/AppDelegate.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/Diagnostics/blob/aa671cd25c3f6eeadce98b9e239246cda8a632a3/Example/Diagnostics-Example/AppDelegate.swift#L31"></span>‘nslog_prohibited’ is not a valid SwiftLint rule. Please remove it from the disable command.<br />
<code>superfluous_disable_command</code> <code>AppDelegate.swift:31</code></td>
    </tr>
  </tbody>
</table>
